{% set name = "helm" %}
{% set version = "3.18.0" %}
{% set pkg_src = os.sep.join(["src", "k8s.io", name]) %}

package:
  name: kubernetes-{{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  - url: https://github.com/helm/helm/archive/v{{ version }}.tar.gz
    sha256: a5555ae9160aa94260a9d40924cda0720f25bb772b5206937f5c8470f7e68307
    patches:
      - 0001-Allow-setting-VERSION_METADATA-GIT_DIRTY.patch
    folder: {{ pkg_src }}

build:
  number: 0
  script:
    - pushd {{ pkg_src }}
    - make build BINARY_VERSION=v{{ version }} VERSION_METADATA=conda-forge GIT_DIRTY=clean
    - make test-unit                                                    # [unix and not arm64]
    - go-licenses save ./cmd/helm --save_path ../../../license-files
    - pushd bin
    - mkdir {{ target_gobin }}
    - cp helm {{ target_gobin }}helm{{ target_goexe }}
    # Clear cache to avoid excessive file not removable warnings
    - chmod -R u+w $(go env GOPATH) && rm -r $(go env GOPATH)           # [unix]

requirements:
  build:
    - {{ compiler('go') }}
    - go-licenses
    - go-gox
    - make
    - git

test:
  requires:
    - ripgrep
  commands:
    - helm --help
    - helm version
    - helm version | rg {{ version }}
    - helm version | rg conda-forge
    - helm version | rg --invert-match dirty | rg --invert-match unreleased

about:
  home: https://www.helm.sh
  license: Apache-2.0
  license_family: Apache
  license_file:
    - {{ pkg_src }}/LICENSE
    - license-files/
  summary: Helm is a package manager for kubernetes
  doc_url: https://docs.helm.sh
  dev_url: https://github.com/helm/helm

extra:
  recipe-maintainers:
    - sodre
    - dhirschfeld
    - dbast
