{% set name = "helm" %}
{% set version = "3.16.2" %}
{% set pkg_src = os.sep.join(["src", "k8s.io", name]) %}

package:
  name: kubernetes-{{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  - url: https://github.com/helm/helm/archive/v{{ version }}.tar.gz
    sha256: c9d8360dcd720c47ca13ded8739d693f25e0f12234054c8ebbf027a5ceafe76d
    folder: {{ pkg_src }}

build:
  number: 1
  script:
    - pushd {{ pkg_src }}
    - make build
    - make test-unit                                                    # [unix and not arm64]
    - go-licenses save ./cmd/helm --save_path ../../../license-files
    - pushd bin
    - mkdir {{ target_gobin }}
    - cp helm {{ target_gobin }}helm{{ target_goexe }}
    # Clear cache to avoid excessive file not removable warnings
    - chmod -R u+w $(go env GOPATH) && rm -r $(go env GOPATH)           # [unix]

requirements:
  build:
    - {{ compiler('go') }}
    - go-licenses
    - go-gox
    - make

test:
  commands:
    - helm --help
    - helm version

about:
  home: https://www.helm.sh
  license: Apache-2.0
  license_family: Apache
  license_file:
    - {{ pkg_src }}/LICENSE
    - license-files/
  summary: Helm is a package manager for kubernetes
  doc_url: https://docs.helm.sh
  dev_url: https://github.com/helm/helm

extra:
  recipe-maintainers:
    - sodre
    - dhirschfeld
    - dbast
