{% set name = "helm" %}
{% set goname = "k8s.io/" + name %}

{% set version = "3.15.3" %}
{% set pkg_src = ('src/'+goname).replace("/", "\\" if win else "/") %}

package:
  name: kubernetes-{{ name|lower }}
  version: {{ version }}

source:
  - url: https://get.helm.sh/helm-v{{ version }}-windows-amd64.zip  # [win]
    sha256: fd857635bbb38b20a91731e5d084c2e21503b0f797b153e3246de01676819f23  # [win]
    folder: {{ pkg_src }}  # [win]
  - url: https://github.com/helm/helm/archive/v{{ version }}.tar.gz  # [not win]
    sha256: f4eb30fa8285091ceffba16cf5ad7ec4b444897bd1df615af4bef3842f6d6d0e  # [not win]
    folder: {{ pkg_src }}  # [not win]


build:
  number: 0
  script:
    - pushd {{ pkg_src }}
    - export USER=$(id -u -n)  # [osx]
    - make build  # [unix]
    - make test-unit  # [unix and not arm64]
    - pushd bin  # [unix]

    - mkdir {{ target_gobin }}
    - cp helm{{ target_goexe }} {{ target_gobin }}

requirements:
  build:
    - {{ compiler('go') }} >=1.15.7
    - go-gox
    - make  # [unix]
    - m2-coreutils  # [win]
test:
  commands:
    - helm --help

about:
  home: https://www.helm.sh
  license: Apache-2.0
  license_family: Apache
  license_file: {{ pkg_src }}/LICENSE
  summary: Helm is a package manager for kubernetes
  doc_url: https://docs.helm.sh
  dev_url: https://github.com/helm/helm

extra:
  recipe-maintainers:
    - sodre
    - dhirschfeld
