{% set name = "helm" %}
{% set goname = "k8s.io/" + name %}

{% set version = "3.7.2" %}
{% set pkg_src = ('src/'+goname).replace("/", "\\" if win else "/") %}

package:
  name: kubernetes-{{ name|lower }}
  version: {{ version }}

source:
  - folder: {{ pkg_src }}
    url: https://github.com/helm/helm/archive/v{{ version }}.tar.gz  # [not win]
    sha256: d04175807c2948261517b58120a0810ec20b92c0058acb040e973d0b9de7b08d  # [not win]
    url: https://get.helm.sh/helm-v{{ version }}-windows-amd64.zip  # [win]
    sha256: 299165f0af46bece9a61b41305cca8e8d5ec5319a4b694589cd71e6b75aca77e  # [win]

build:
  number: 0
  script:
    - pushd {{ pkg_src }}
    - export USER=$(id -u -n)  # [osx]
    - make build test-unit  # [unix]
    - pushd bin  # [unix]

    - mkdir {{ target_gobin }}
    - cp helm{{ target_goexe }} {{ target_gobin }}

requirements:
  build:
    - {{ compiler('go') }} >=1.15.7
    - go-gox
    - make  # [unix]
    - m2-coreutils  # [win]
test:
  commands:
    - helm --help

about:
  home: https://www.helm.sh
  license: Apache-2.0
  license_family: Apache
  license_file: {{ pkg_src }}/LICENSE
  summary: Helm is a package manager for kubernetes
  doc_url: https://docs.helm.sh
  dev_url: https://github.com/helm/helm

extra:
  recipe-maintainers:
    - sodre
    - dhirschfeld
