{% set name = "helm" %}
{% set goname = "k8s.io/" + name %}

{% set version = "3.10.3" %}
{% set pkg_src = ('src/'+goname).replace("/", "\\" if win else "/") %}

package:
  name: kubernetes-{{ name|lower }}
  version: {{ version }}

source:
  - folder: {{ pkg_src }}
    url: https://github.com/helm/helm/archive/v{{ version }}.tar.gz  # [not win]
    sha256: a61ede2b1b9a0d3a7c1cc19cca99db109eb5b787eee0e147bd3bfa2c4e337eb1  # [not win]
    url: https://get.helm.sh/helm-v{{ version }}-windows-amd64.zip  # [win]
    sha256: 5d97aa26830c1cd6c520815255882f148040587fd7cdddb61ef66e4c081566e0  # [win]

build:
  skip: true  # [osx]
  number: 0
  script:
    - pushd {{ pkg_src }}
    - export USER=$(id -u -n)  # [osx]
    - make build  # [unix]
    - make test-unit  # [unix and not arm64]
    - pushd bin  # [unix]

    - mkdir {{ target_gobin }}
    - cp helm{{ target_goexe }} {{ target_gobin }}

requirements:
  build:
    - {{ compiler('go') }} >=1.15.7
    - go-gox
    - make  # [unix]
    - m2-coreutils  # [win]
test:
  commands:
    - helm --help

about:
  home: https://www.helm.sh
  license: Apache-2.0
  license_family: Apache
  license_file: {{ pkg_src }}/LICENSE
  summary: Helm is a package manager for kubernetes
  doc_url: https://docs.helm.sh
  dev_url: https://github.com/helm/helm

extra:
  recipe-maintainers:
    - sodre
    - dhirschfeld
