{% set name = "kubernetes-helm" %}
{% set version = "2.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/kubernetes/helm/archive/v{{ version }}.tar.gz  # [not win]
  url: https://storage.googleapis.com/{{ name }}/helm-v{{ version }}-windows-amd64.tar.gz  # [win]

  sha256: 5bfc368df2551d228a941286a59f31c53faebdc7a02edda2dc6df33998d1a438  # [not win]
  sha256: d0eeb122505cc833e526c8649c13d963103a7a769563b1cb27f8f7399e6e7c8f  # [win]

build:
  skip: True  # [win32]
  number: 1000

requirements:
  build:
    - {{ compiler('go') }}  # [not win]
    - {{ compiler('c') }}
    - make  # [not win]
  host:
    - git  # [not win]
    - mercurial  # [not win]

test:
  commands:
    - helm --help
    - tiller -version  # [linux]

about:
  home: https://www.helm.sh
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Helm is a package manager for kubernetes
  doc_url: https://docs.helm.sh
  dev_url: https://github.com/kubernetes/helm

extra:
  recipe-maintainers:
    - sodre
