{% set name = "helm" %}
{% set goname = "k8s.io/" + name %}

{% set version = "3.15.0" %}
{% set pkg_src = ('src/'+goname).replace("/", "\\" if win else "/") %}

package:
  name: kubernetes-{{ name|lower }}
  version: {{ version }}

source:
  - folder: {{ pkg_src }}
    url: https://get.helm.sh/helm-v{{ version }}-windows-amd64.zip  # [win]
    sha256: e4a8ec10b6a7ad77792f616be131f40e361da4f034dd3f2ab214e932023146a3  # [win]
    url: https://github.com/helm/helm/archive/v{{ version }}.tar.gz  # [not win]
    sha256: e4a8ec10b6a7ad77792f616be131f40e361da4f034dd3f2ab214e932023146a3  # [not win]


build:
  number: 0
  script:
    - pushd {{ pkg_src }}
    - export USER=$(id -u -n)  # [osx]
    - make build  # [unix]
    - make test-unit  # [unix and not arm64]
    - pushd bin  # [unix]

    - mkdir {{ target_gobin }}
    - cp helm{{ target_goexe }} {{ target_gobin }}

requirements:
  build:
    - {{ compiler('go') }} >=1.15.7
    - go-gox
    - make  # [unix]
    - m2-coreutils  # [win]
test:
  commands:
    - helm --help

about:
  home: https://www.helm.sh
  license: Apache-2.0
  license_family: Apache
  license_file: {{ pkg_src }}/LICENSE
  summary: Helm is a package manager for kubernetes
  doc_url: https://docs.helm.sh
  dev_url: https://github.com/helm/helm

extra:
  recipe-maintainers:
    - sodre
    - dhirschfeld
