{% set name = "helm" %}
{% set goname = "k8s.io/" + name %}

{% set version = "3.7.1" %}
{% set pkg_src = ('src/'+goname).replace("/", "\\" if win else "/") %}

package:
  name: kubernetes-{{ name|lower }}
  version: {{ version }}

source:
  - folder: {{ pkg_src }}
    url: https://github.com/helm/helm/archive/v{{ version }}.tar.gz  # [not win]
    sha256: 5243dd0e07840404a7d19ca0917b2202ee3a5ad70a081cfa455ffd705a8d3624  # [not win]
    url: https://get.helm.sh/helm-v{{ version }}-windows-amd64.zip  # [win]
    sha256: e057f24032a6b5602edccfdf8fa191568471fce29aada86d6f7f46fc611a3258  # [win]

build:
  number: 0
  script:
    - pushd {{ pkg_src }}
    - export USER=$(id -u -n)  # [osx]
    - make build test-unit  # [unix]
    - pushd bin  # [unix]

    - mkdir {{ target_gobin }}
    - cp helm{{ target_goexe }} {{ target_gobin }}

requirements:
  build:
    - {{ compiler('go') }} >=1.15.7
    - go-gox
    - m2-coreutils  # [win]
test:
  commands:
    - helm --help

about:
  home: https://www.helm.sh
  license: Apache-2.0
  license_family: Apache
  license_file: {{ pkg_src }}/LICENSE
  summary: Helm is a package manager for kubernetes
  doc_url: https://docs.helm.sh
  dev_url: https://github.com/helm/helm

extra:
  recipe-maintainers:
    - sodre
    - dhirschfeld
