schema_version: 1

context:
  name: kubernetes-helm
  version: 4.2.4

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/helm/helm/archive/v${{ version }}.tar.gz
  sha256: f1a1aa56fff071cfa1eecc18c6a7212b2e5c7a0a123fd8e4dcae620bd51b4286
  patches:
    - 0001-Allow-setting-VERSION_METADATA-GIT_DIRTY.patch
  target_directory: src

build:
  number: 1
  script:
    - cd src
    - make build BINARY_VERSION=v${{ version }} VERSION_METADATA=conda-forge GIT_DIRTY=clean
    - if: build_platform == target_platform and unix and not (aarch64 or arm64 or ppc64le)
      then: make test-unit
    - go-licenses save ./cmd/helm --save_path ../license-files
    - if: unix
      then:
        - mkdir -p "$PREFIX/bin"
        - cp bin/helm "$PREFIX/bin/helm"
    - if: win
      then:
        - if not exist "%LIBRARY_BIN%" mkdir "%LIBRARY_BIN%"
        - copy bin\helm "%LIBRARY_BIN%\helm.exe"

requirements:
  build:
    - ${{ compiler('go') }}
    - go-licenses
    - make
    - git

tests:
  - package_contents:
      bin:
        - helm
  - requirements:
      run:
        - ripgrep
    script:
      - helm --help
      - helm version
      - helm version | rg ${{ version }}
      - helm version | rg conda-forge
      - helm version | rg --invert-match dirty | rg --invert-match unreleased

about:
  homepage: https://www.helm.sh
  documentation: https://docs.helm.sh
  repository: https://github.com/helm/helm
  license: Apache-2.0
  license_family: Apache
  license_file:
    - src/LICENSE
    - license-files/
  summary: Helm is a package manager for kubernetes

extra:
  recipe-maintainers:
    - sodre
    - dhirschfeld
    - dbast
