appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: OvyVit/qfMT3ozhwgZEDFUA60MHjR02cHvk5mOTH5yrBm5Nywfe4yoUi5lqd7rd4Fa2aIVgXdgZwj7kLTGU2hPGaOujfr5atPmdeeSaQ4b8TyqyQFuQk9LeCnYMBuh1RfVlD8bJBxazKmTlsmNYHE59xwz27GiCKlfQunuKaZKzXtFIzHs9oNEaloDVmSo1y1ijGkjm5p58T0MpF2EYKx10OPgkuZ/M/2aKZSB16LSUTJNgVPDmqJkNLWShM7I/cR9n411p/Pa7Qb/X6HxBFp1nIusahxCrxhcUBlKcizT1UkWuXV4lmxThBJf8sDAMUGrqJgSbdUpCgC0j/yedQ4weCccDDo33HeQsCUJVlB6FK/9F5nPbfbiCW/fQMgMaVeQj1W8jcanahz0pWwbJYzYjLP8L9R8536szz9nxjofS5BD2nYaR5+SEx4dWmrtH281ZQZjfohoxOF0Mvq52SPz5nat9CJIYeuadqkVIpcUaF6Wsh8wEHcnveHI7aqk6qc11+vDc/w9xiZ5dI1xI8SoRtrLJ0j2iSqi0kvAj+3CbFzV+AyxgmYiTNdT2juPSmojZuSpNVD41FS8Zg6zF5CmSYJzDobZC3NAqG74BymltZgakrHZkjIenNcfWCSSDHqof59hM1ZrvAwRkfvc7VPZhCDUz2YjOo1vENNQqFXIw=}
